/// 1. OBJECT NGÀY ÂM LỊCH
class LunarDate {
  final int day;
  final int month;
  final int year;

  const LunarDate({required this.day, required this.month, required this.year});

  String get formatted =>
      '${day.toString().padLeft(2, '0')}/${month.toString().padLeft(2, '0')}/${year.toString()}';

  String get displayShort =>
      '${day.toString().padLeft(2, '0')}/${month.toString().padLeft(2, '0')} Âm lịch';

  factory LunarDate.fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return const LunarDate(day: 0, month: 0, year: 0);
    }
    return LunarDate(
      day: json['day'] is int ? json['day'] : int.tryParse('${json['day']}') ?? 0,
      month: json['month'] is int ? json['month'] : int.tryParse('${json['month']}') ?? 0,
      year: json['year'] is int ? json['year'] : int.tryParse('${json['year']}') ?? 0,
    );
  }

  Map<String, dynamic> toJson() => {
    'day': day,
    'month': month,
    'year': year,
  };
}

/// 2. EVENT MODEL CHÍNH (ĐỒNG BỘ BACKEND FASTAPI & MYSQL)
class EventModel {
  final String id;
  final String title;
  final String eventType; // "birthday", "death_anniversary", "custom", "meeting", "worship"
  final LunarDate lunarDate;
  final DateTime? solarDate;
  final String note;
  final String creatorName;
  final String creatorAvatarUrl;
  final String dateRange;
  final String time;
  final DateTime date; // Ngày khớp với solarDate để hiển thị lịch
  final bool isNotified;
  final bool isAutoGenerated;
  final int? memberId;
  final int? familyId;
  final String? location;

  EventModel({
    required this.id,
    required this.title,
    this.eventType = 'custom',
    required this.dateRange,
    required this.time,
    required this.date,
    this.lunarDate = const LunarDate(day: 0, month: 0, year: 0),
    this.solarDate,
    this.note = '',
    this.creatorName = '',
    this.creatorAvatarUrl = '',
    this.isNotified = false,
    this.isAutoGenerated = false,
    this.memberId,
    this.familyId,
    this.location,
  });

  // Getters hỗ trợ hiển thị UI
  String get dayString => date.day.toString().padLeft(2, '0');
  String get monthLabel => 'THÁNG ${date.month.toString().padLeft(2, '0')}';
  String get shortMonth => date.month.toString().padLeft(2, '0');
  String get yearLabel => date.year.toString();
  String get solarDateLabel {
    if (solarDate == null) return '';
    return '${solarDate!.day.toString().padLeft(2, '0')}/${solarDate!.month.toString().padLeft(2, '0')}/${solarDate!.year}';
  }

  // Getters phân loại sự kiện
  bool get isBirthday => eventType == 'birthday';
  bool get isDeathAnniversary => eventType == 'death_anniversary';

  // Hàm chuyển đổi từ JSON API
  factory EventModel.fromJson(Map<String, dynamic> json) {
    DateTime parsedDate;
    if (json['date'] != null) {
      try {
        parsedDate = DateTime.parse(json['date']);
      } catch (_) {
        parsedDate = DateTime.now();
      }
    } else {
      parsedDate = DateTime.now();
    }

    DateTime? parsedSolarDate;
    if (json['solarDate'] != null && json['solarDate'].toString().isNotEmpty) {
      final s = json['solarDate'].toString();
      try {
        if (s.contains('/')) {
          final parts = s.split('/');
          if (parts.length == 3) {
            parsedSolarDate = DateTime(
              int.parse(parts[2]),
              int.parse(parts[1]),
              int.parse(parts[0]),
            );
          }
        } else {
          parsedSolarDate = DateTime.parse(s);
        }
      } catch (_) {
        parsedSolarDate = parsedDate;
      }
    }

    return EventModel(
      id: json['id']?.toString() ?? '',
      title: json['title']?.toString() ?? '',
      eventType: json['eventType']?.toString() ?? 'custom',
      lunarDate: LunarDate.fromJson(json['lunarDate'] as Map<String, dynamic>?),
      solarDate: parsedSolarDate ?? parsedDate,
      dateRange: json['dateRange']?.toString() ?? '',
      time: json['time']?.toString() ?? '08:00 - 11:30',
      date: parsedDate,
      note: json['note']?.toString() ?? '',
      creatorName: json['creatorName']?.toString() ?? '',
      creatorAvatarUrl: json['creatorAvatarUrl']?.toString() ?? '',
      isNotified: json['isNotified'] == true,
      isAutoGenerated: json['isAutoGenerated'] == true,
      memberId: json['memberId'] is int ? json['memberId'] : int.tryParse('${json['memberId']}'),
      familyId: json['familyId'] is int ? json['familyId'] : int.tryParse('${json['familyId']}'),
      location: json['location']?.toString(),
    );
  }

  // Hàm chuyển đổi sang JSON gửi lên Backend
  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'eventType': eventType,
      'familyId': familyId,
      'memberId': memberId,
      'lunarDay': lunarDate.day > 0 ? lunarDate.day : null,
      'lunarMonth': lunarDate.month > 0 ? lunarDate.month : null,
      'lunarYear': lunarDate.year > 0 ? lunarDate.year : null,
      'solarDate': solarDateLabel.isNotEmpty ? solarDateLabel : null,
      'time': time,
      'location': location,
      'note': note,
    };
  }

  // Hàm sao chép & chỉnh sửa object
  EventModel copyWith({
    String? id,
    String? title,
    String? eventType,
    LunarDate? lunarDate,
    DateTime? solarDate,
    String? note,
    String? creatorName,
    String? creatorAvatarUrl,
    String? dateRange,
    String? time,
    DateTime? date,
    bool? isNotified,
    bool? isAutoGenerated,
    int? memberId,
    int? familyId,
    String? location,
  }) {
    return EventModel(
      id: id ?? this.id,
      title: title ?? this.title,
      eventType: eventType ?? this.eventType,
      lunarDate: lunarDate ?? this.lunarDate,
      solarDate: solarDate ?? this.solarDate,
      note: note ?? this.note,
      creatorName: creatorName ?? this.creatorName,
      creatorAvatarUrl: creatorAvatarUrl ?? this.creatorAvatarUrl,
      dateRange: dateRange ?? this.dateRange,
      time: time ?? this.time,
      date: date ?? this.date,
      isNotified: isNotified ?? this.isNotified,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      memberId: memberId ?? this.memberId,
      familyId: familyId ?? this.familyId,
      location: location ?? this.location,
    );
  }

  /// DỮ LIỆU SỰ KIỆN MẶC ĐỊNH
  static const List<EventModel> sampleEvents = [];
}
